"use client";

import { useEffect, useState } from "react";
import AppSidebar from "../components/AppSidebar";
import GlobalAppearanceControl from "../components/GlobalAppearanceControl";

type AnalyticsData = { status?: string; totalReplies?: number; replies7d?: number; trend?: number[]; aiArkCalls?: number; aiArkSuccesses?: number; aiArkFailures?: number; aiArkTrend?: number[]; aiArkTrendLabels?: string[]; clientLoad?: Array<{ name: string; leads: number }> };

export default function AnalyticsPage() {
  const [data, setData] = useState<AnalyticsData>({});
  useEffect(() => { fetch("/api/analytics", { cache: "no-store" }).then((response) => response.json()).then(setData).catch(() => setData({ status: "error" })); }, []);
  const trend = data.trend ?? [];
  const max = Math.max(...trend, 1);
  const aiArkTrend = data.aiArkTrend ?? [];
  const aiArkMax = Math.max(...aiArkTrend, 1);
  return <div className="app-shell"><AppSidebar/><section className="main-area"><header className="topbar"><div className="crumb"><span>Reply Radar</span><strong>› Analytics</strong></div><div className="top-actions"><GlobalAppearanceControl /></div></header><main className="admin-shell analytics-shell"><section className="admin-content"><div className="admin-heading"><div><div className="eyebrow"><span className="live-dot"/>PERFORMANCE</div><h1>Analytics</h1><p>Live metrics from connected workspaces.</p></div></div><div className="workspace-cards"><Stat label="Replies · 7 days" value={data.replies7d == null ? "—" : String(data.replies7d)} /><Stat label="Total replies" value={data.totalReplies == null ? "—" : String(data.totalReplies)} /><Stat label="AI Ark API calls" value={data.aiArkCalls == null ? "—" : String(data.aiArkCalls)} /><Stat label="Workspaces" value={data.clientLoad == null ? "—" : String(data.clientLoad.length)} /></div><div className="admin-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Reply activity</h2><p>Daily message volume from synced data.</p></div><span className="saved-dot">{data.status ?? "Loading"}</span></div>{trend.length ? <div className="bar-chart">{trend.map((value, index) => <div key={index} className="bar-col"><i style={{ height: `${(value / max) * 100}%` }} /><small>{index + 1}</small></div>)}</div> : <p className="empty-state">No synced analytics data is available yet.</p>}</section><section className="admin-panel"><div className="panel-heading"><div><h2>Workspace comparison</h2><p>Conversation volume by workspace.</p></div></div>{data.clientLoad?.length ? data.clientLoad.map((item) => <div className="timeline-row" key={item.name}><i style={{ background: "var(--accent)" }} /><span><strong>{item.name}</strong><small>{item.leads} conversations</small></span></div>) : <p className="empty-state">No workspace data is available yet.</p>}</section><section className="admin-panel"><div className="panel-heading"><div><h2>AI Ark enrichment calls</h2><p>Actual external People Search requests. Cache hits are intentionally excluded.</p></div><span className="saved-dot">{data.aiArkSuccesses ?? 0} succeeded · {data.aiArkFailures ?? 0} failed</span></div>{aiArkTrend.length ? <div className="bar-chart">{aiArkTrend.map((value, index) => <div key={index} className="bar-col" title={`${data.aiArkTrendLabels?.[index] ?? ""}: ${value} calls`}><i style={{ height: `${(value / aiArkMax) * 100}%` }} /><small>{index % 2 === 0 ? data.aiArkTrendLabels?.[index] : ""}</small></div>)}</div> : <p className="empty-state">No AI Ark API calls have been recorded yet.</p>}</section></div></section></main></section></div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="workspace-card"><div className="workspace-card-top"><span className="health-state ready">LIVE</span></div><strong>{value}</strong><small>{label}</small></div>; }
